service: your-service-name

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  environment:
    PORT: 8000

functions:
  app:
    handler: src/handler.main
    events:
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-offline
